### ISSUE TITLE
No longer highlighted background on code blocks

### ISSUE THREAD

**Issue by usernamehw** [mjbvz/vscode-markdown-shiki#4]
There's different background on markdown code blocks by default:
![Screenshot (95)](https://user-images.githubusercontent.com/9638156/68072499-8d0f7400-fd97-11e9-9bca-ad263b9d2675.png)

When extension enabled it's no longer true:
![Screenshot (96)](https://user-images.githubusercontent.com/9638156/68072521-cf38b580-fd97-11e9-9cfa-0dea00a821d3.png)

**Comment by larhun** [comment]
Here some code colors are lost on line 6:

![image](https://user-images.githubusercontent.com/33022639/68074980-10ce5e00-fda2-11e9-959c-9c3eb603dfac.png)

![image](https://user-images.githubusercontent.com/33022639/68074990-47a47400-fda2-11e9-99c3-3048f8c564a0.png)

**Comment by usernamehw** [comment]
@larhun This issue is about background of the block. For color inconsistencies you should create a separate issue, but foreground just might get fixed by this Pull Request: https://github.com/mjbvz/vscode-markdown-shiki/pull/3
